name 'om-env-kako'
maintainer 'Peter Adkins'
maintainer_email 'pete@kernelpicnic.net'
description 'Installs/Configures an kako node'
long_description 'Installs/Configures an kako node'
version '1.0.0'

depends 'apt', '= 5.0.0'
depends 'ntp', '= 3.2.0'
depends 'sysctl', '= 0.8.0'
depends 'iptables', '= 4.3.1'
depends 'poise-python', '= 1.5.1'
